### ISSUE TITLE
Creative search tab

### ISSUE THREAD

**Issue by 2929762171** [PssbleTrngle/Brazier#101]
### What happened?

Appears on every page and overlays others.
![problem](https://github.com/PssbleTrngle/Brazier/assets/98941945/358c49d4-0cda-4ce3-aa38-e5ff7f514728)

### Mod Version

brazier-3.0.10-forge

### Minecraft Version

1.16

### Minecraft Loader

Forge

### Fabric/Forge Version

36.2.39

**Comment by PssbleTrngle** [comment]
I'm sorry, what exactly is the problem?

**Comment by 2929762171** [comment]
With this mod 
![image](https://github.com/PssbleTrngle/Brazier/assets/98941945/5950366f-ad07-4698-923b-824a165b7874)
![image](https://github.com/PssbleTrngle/Brazier/assets/98941945/cda6f5c7-0557-43b2-979b-54f2fa3d65b6)
![image](https://github.com/PssbleTrngle/Brazier/assets/98941945/d2cdcc7e-0350-4d04-b21c-e0a2f50bde72)
![image](https://github.com/PssbleTrngle/Brazier/assets/98941945/6c597457-1d2d-4db4-a7aa-a45ebbca2643)
Without this mod
![image](https://github.com/PssbleTrngle/Brazier/assets/98941945/46ffa25f-61a1-493a-8bf4-6cd075813737)
![image](https://github.com/PssbleTrngle/Brazier/assets/98941945/854b788b-501d-4f74-89a0-14362eb3688e)
![image](https://github.com/PssbleTrngle/Brazier/assets/98941945/9ca26595-c0f3-4420-9661-e7796eb64964)

**Comment by PssbleTrngle** [comment]
Ah, now I see it, but I would be very surprised if this has anything to do with this mod to be honest, is it fixed by removing brazier?
