### ISSUE TITLE
BlackList

### ISSUE THREAD

**Issue by NicolasLasch** [PssbleTrngle/Brazier#106]
### What happened?

Hello I'm trying to acces the blacklist on the brazier mod because all moded mobs are still spawning, but I don't know where it is. Looking through all the files but nothing in config beside brazier-client.toml and brazier-common.toml. Those have no informations about black-list.

### Mod Version

4.2.0

### Minecraft Version

1.18

### Minecraft Loader

Fabric

### Fabric/Forge Version

40.2.14

**Comment by PssbleTrngle** [comment]
the black/whitelists are configured using entity tags and can be changed with a datapack. [You can find the default values here](https://github.com/PssbleTrngle/Brazier/blob/1.19.x/common/src/main/resources/data/brazier/tags/entity_types/brazier_blacklist.json)
