### ISSUE TITLE
I've checked 3 mansions and so far no Crazed have spawned. version 1.2.0

### ISSUE THREAD

**Issue by Boodlyneck** [PssbleTrngle/Brazier#20]
I've been using `/execute as @e[type=brazier:crazed] run say hello` when I get to the mansion to make sure I'm not missing them.

**Comment by PssbleTrngle** [comment]
That's weird, they should instead of an evoked every now and than, but the chance surely should not be this low. I will give it a look

**Comment by PssbleTrngle** [comment]
I did some testing and I always got about on crazed per mansion.
There is a new version containing an config option to modify the spawn chance, but I have also increased it by a bit.
