### ISSUE TITLE
Allow mob farms

### ISSUE THREAD

**Issue by OGitsBoondock** [PssbleTrngle/Brazier#27]
I do think it would be cool if somehow there was a capstone (lodestone maybe?) that would allow only certain mobs to spawn. For swamp slime farms this would be amazing. From test it seems like an awesome mod and much more vanilla friendly then the torch mod that does something similar

**Comment by PssbleTrngle** [comment]
I have been thinking about a form of control to allow things like mob farms in areas where you don't want any other mobs to spawn.
I think being able to choose whether the brazier works only above, below or both would solve it

**Comment by OGitsBoondock** [comment]
Happy to test it out! It will certainly help to ensure building mob farms without clearing cave systems would be a time saver for me.

**Comment by PssbleTrngle** [comment]
You now have 2 options to enable mob farms:
1. Set the `protectAbove` option in the server config to false, this will enable mob farms built above the height of the brazier block
2. Use the new "cursed ash", which bypasses brazier protection on the block it is placed
