### ISSUE TITLE
No Visible Protection Area

### ISSUE THREAD

**Issue by Danickar** [PssbleTrngle/Brazier#29]
While holding the appropriate torch I can not see any sort of visual outline of the protection area. Also, does the protection area repel/remove mobs that walk into it or only keep them from spawning? I still have mobs all over the area around my brazier, just having a hard time telling if they are walking in or spawning in.

**Version**
Forge Version: 1.16.1-32.0.108 
Mod Version: 1.2.4

**Comment by PssbleTrngle** [comment]
It just prevents spawning
