### ISSUE TITLE
Rename the Crazed to the Sorcerer to keep up with illiger names ending with "er", also when will it be updated to 1.16.3?

### ISSUE THREAD

**Issue by gagedude89** [PssbleTrngle/Brazier#32]
The 1st idea is a simple change, just to make it match up with the other illagers. And on another note, any idea on when the mod will be updated to 1.16.3?

**Comment by PssbleTrngle** [comment]
I agree, I also would like a name anding of "er" but I could not think of anything I liked. Sorcerer was just to bland

**Comment by PssbleTrngle** [comment]
And the mod will update to 1.16.3 no later than the abnormals mods will update to 1.16.3.
Maybe a bit earlier if I'll have some time
