### ISSUE TITLE
Missing Brazier texture

### ISSUE THREAD

**Issue by marcebdev** [PssbleTrngle/Brazier#45]
**Describe the bug**
Seems to be a missing texture on the brazier

**To Reproduce**
I tried a couple configurations and increasing the height to 2 and the issue persisted so it's probably just a missing/broken texture. An example screenshot is provided.

**Expected behavior**
No missing texture.

**Screenshots**
![2020-12-02_22 38 12](https://user-images.githubusercontent.com/20135668/100962592-9915ba00-34f2-11eb-8ad1-9a642da8cc69.png)

**Version**
Forge Version: 35.1.7
Mod Version: 2.1.1

**Comment by PssbleTrngle** [comment]
I think it has something to do with me working on the the texture.

2.1.1 is an alpha build and highly experimental, I would recommend using the beta builds

**Comment by PssbleTrngle** [comment]
Closed in #46
