### ISSUE TITLE
Add a config option to enable/disable Crazed Illagers spawning in raids

### ISSUE THREAD

**Issue by iCeParadox64** [PssbleTrngle/Brazier#51]
**Is your feature request related to a problem? Please describe.**
Crazed Illagers only spawn in woodland mansions, which are ridiculously scarce, and spawn a _minimum_ of 10,000 blocks away from world spawn. And even if you find one, there's not a 100% guarantee that a Crazed Illager will be inside. Sure, you can also find living flames in jungle temples, but those are so rare, I think the last time I found one was literal _years_ ago. All of this makes acquiring living flames _far_ too tedious, in my opinion.

**Describe the solution you'd like.**
The solution is quite simple: add an option in the config file that allows Crazed Illagers to spawn in raids. If this option is set to true, then perhaps a Crazed Villager has a 50% chance of taking the place of an Evoker whenever one spawns in a raid, or some alternative spawning method if you can think of something better. [More info on raid wave spawning here.](https://minecraft.gamepedia.com/Raid#Java_Edition)

**Describe alternatives you've considered.**
This is _technically_ possible with a data pack, but I feel it would be so much simpler and less janky to just have a config option for it.

**Comment by PssbleTrngle** [comment]
I personally wanted the crazed to be another reason to look for and visit a woodlands mansion, but I understand why you'd want this.

**Comment by iCeParadox64** [comment]
I do understand that, but unfortunately, ever since raids were added to the game, I think woodland mansions would need a complete overhaul to be worth finding.
I also assume that making living flames extremely rare was a deliberate choice, and I get that, but everyone plays Minecraft differently, and every modpack has a different style of progression. Adding the option to have crazed illagers spawn in raids would help your mod fit into more peoples' games. The only alternative I've found is [Torchmaster](https://www.curseforge.com/minecraft/mc-mods/torchmaster), but the item that prevents mob spawning is *_way_* too easy to craft, so I don't like it. So please add the raid config option, I would appreciate it a million times over!
