### ISSUE TITLE
[Suggestion] ingame information

### ISSUE THREAD

**Issue by Zygus42** [PssbleTrngle/Brazier#54]
Cool concept, but in a modpack, on a server, people find your items, look at JEI what they can make, see there is no info on what they do, and chuck it in a chest never to be looked at again.  It needs some tooltips or some other ingame way to see what the items do and how to use them.

**Comment by PssbleTrngle** [comment]
I could add an Information entry to the living flame if JEI is present, telling you could create a brazier and what it does

**Comment by PssbleTrngle** [comment]
There is a new release (currently marked as `alpha` on curseforge because I could not do much testing), which includes JEI information for the brazier
