### ISSUE TITLE
Brazier not stoping Vampirism spawning

### ISSUE THREAD

**Issue by Milii20** [PssbleTrngle/Brazier#55]
Greetings! 
First of all, this mod is super useful for stoping pretty much anything evil.

But i found out, if you have the Vampirism mod, it wont block the spawn of vampires or vampire hunters (i mean normal spawnings, not spawners, just random vampires spawning in the dark for example).

May i suggest implementing (if possible) some sort of a list for "stuff you dont want spawning in the radius of the brazier" as a config?

Thank you for making such an amazing mod, way better than other mobs that block spawning stuff.
And Thank you for your time!

**Comment by Milii20** [comment]
I think there seems to be a blacklist coded in (readed the code a bit, and the customization part of the curseforge page)
could you please point me at how to add a mob to said blacklist?

**Comment by PssbleTrngle** [comment]
Using a datapack. The is the entity tag `#brazier:brazier_blacklist`. You can take a look at the default tag which contains the magma cube and the slime [here](https://github.com/PssbleTrngle/Brazier/blob/1.16.3/src/main/resources/data/brazier/tags/entity_types/brazier_blacklist.json)

**Comment by Milii20** [comment]
Thank you very much, all working now and no vampires to be seen!

**Comment by PssbleTrngle** [comment]
If you want to send me the file, I'd include them in the default blacklist

**Comment by Milii20** [comment]
[brazier.zip](https://github.com/PssbleTrngle/Brazier/files/5816568/brazier.zip)

here you go! and thank you again!
