### ISSUE TITLE
can you check the 1.16.5 checkbox for the latest 1.16.4 file (if compatible)...

### ISSUE THREAD

**Issue by Wedge1453** [PssbleTrngle/Brazier#56]
...so that it appears while browsing for mods in 1.16.5 profiles in the curse app.

**Comment by PssbleTrngle** [comment]
Will release a new version soon, will include 1.16.5

**Comment by Wedge1453** [comment]
great! just to let you know the current 1.16.4 version works fine in 1.16.5

**Comment by PssbleTrngle** [comment]
I still have it marked as `alpha` on curseforge because I could not do much testing with the actual mod jar, but there is now a 1.16.5 file
