### ISSUE TITLE
Minecraft Boot Error with latest version

### ISSUE THREAD

**Issue by zachsai** [PssbleTrngle/Brazier#67]
**Describe the bug**
Minecraft loading error
**To Reproduce**
https://gist.github.com/celsiusqc/10ae24e918d501823d26b7078a17bab3
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/63996164/112390368-8fe07100-8ccc-11eb-861f-ff490600b07c.png)

**Version**
Forge Version: 36.0,61
Mod Version: 3.0.0

**Comment by PssbleTrngle** [comment]
Looks like the Java version I used to build it was to high

**Comment by PssbleTrngle** [comment]
If you could try again with version 3.0.1 it should work

**Comment by Wedge1453** [comment]
I second this, 3.0.0 crashes and generates a crash log, 3.0.1 closes the client and doesn't generate a crash log... I'll stick to 2.3.0 for now
[crash-2021-03-25_19.25.44-fml.txt](https://github.com/PssbleTrngle/Brazier/files/6207499/crash-2021-03-25_19.25.44-fml.txt)

**Comment by PssbleTrngle** [comment]
Thanks for the info, 3.0.* are alpha versions for now because I could not do any testing for now.
Sticking with 2.3.0 for now should work fine, as the only changes for now are internal redesigns

**Comment by Wedge1453** [comment]
by the way you can check the 1.16.5 checkbox for 2.3.0 version so that it appears while browsing for mods in 1.16.5 profiles in the curse forge app, I tested it in 1.16.5 and it works
