### ISSUE TITLE
crash forge 1.16.5

### ISSUE THREAD

**Issue by Schmugo** [PssbleTrngle/Brazier#70]
java.lang.NoClassDefFoundError:me/shedaniel/autoconfig/ConfigData

**Comment by PssbleTrngle** [comment]
latest version?
and you have cloth config too?

**Comment by ChaosArtist** [comment]
i have that same issue

**Comment by PssbleTrngle** [comment]
This issue should be fixed, like the linked issue when using the latest version of all  the mods.
Have you tried that?
