### ISSUE TITLE
java.lang.NoClassFoundError: me/shedaniel/autoconfig/ConfigData

### ISSUE THREAD

**Issue by hdallp** [PssbleTrngle/Brazier#71]
**Describe the bug**
Brazier (brazier) has failed to load correctly
`java.lang.NoClassFoundError: me/shedaniel/autoconfig/ConfigData`

**To Reproduce**
Error has occurred during loading

**Version**
Modloader: Forge
Modloader Version: Forge 36.1.2
Mod Version: 3.0.4 (For 1.16.5)

I Saw on [This same Issue](https://github.com/PssbleTrngle/Brazier/issues/70) U said something about cloth config
I Downloaded it and now the error is: 
`java.lang.NoClassFoundError: me/shedaniel/architectury/hooks/TagHooks`

**Comment by PssbleTrngle** [comment]
Duplicate of #70 I think

**Comment by PssbleTrngle** [comment]
Which version of cloth config have you installed?

**Comment by PssbleTrngle** [comment]
And do you have architectury installed too?

**Comment by hdallp** [comment]
I have the latest version of cloth config (v4.11.19), I had version 1.5.109
of the architectury API, so I updated it to the latest one (1.10.139) and
everything worked !
