### ISSUE TITLE
Clarification Requests

### ISSUE THREAD

**Issue by itsNordLord** [PssbleTrngle/Brazier#73]
Hello, this is half question and half feature request.

I am writing a Patchouli guidebook for your wonderful mod to include in my modpack. I would like to mention that calling both the multiblock structure _and_ the actual brazier block "Brazier" is pretty confusing.

Perhaps this is a symptom of "_if you say any word too many times it starts to sound like gibberish_", but it seems inelegant to explain to someone that they must craft the Brazier in order to build the Brazier. 

Example alternatives:

- Living Flame Pedestal
- Cauldron of Fire
- Brazier Centerpiece

I am also confused about a few items, and I would like to include them in the guidebook to flesh it out a bit more.

**1.** How do you use Cursed Ash? I've tried placing it on top of and below blocks with no success:

![image](https://user-images.githubusercontent.com/68762570/119737565-5646f600-be34-11eb-8133-5ae0e0339617.png)

**2.** Does the Living Lantern have any uses? It doesnt seem to activate the radius particles like its ingredient Living Torch does

**Comment by PssbleTrngle** [comment]
I guess the brazier/brazier stuff can be confusing, but on the other hand it's the same for the beacon and the conduit. 

Cursed ash allows mobs to spawn on the block it's placed on, even in the range of an active brazier.
The living lantern is purely decorative, but I should probably also highlight the brazier range, seems like I missed that.

Hope I could help!

**Comment by itsNordLord** [comment]
> 
> 
> I guess the brazier/brazier stuff can be confusing, but on the other hand it's the same for the beacon and the conduit.
> 
That.. is an excellent point I had not considered. I have made neither of those buildings in quite some time lol. I suppose I'll reference the Wiki's phrasing then. Thanks :)
>
> Cursed ash allows mobs to spawn on the block it's placed on, even in the range of an active brazier.
>
I thought so, does anything look wrong with the exposed ash in the original image? I'm running just a barebones mod setup for Brazier and I cant get mobs to spawn where the Cursed Ash is placed.
>
> The living lantern is purely decorative, but I should probably also highlight the brazier range, seems like I missed that.
>
Good to know. Alternatively, you could use it to solve a different problem:

In an extremely hypothetical scenario where one does not know if they are in range of a Brazier (ex if the Brazier and player are deep underground so you cannot easily walk in one direction to find the "range"), you could just have the lantern turn on or off depending on if it is in range of an active Brazier or not. That would be helpful. 

Perhaps that is better suited for a block that would typically turn on and off, like a Redstone Lamp alternative.

**Comment by PssbleTrngle** [comment]
Weird, do you mind telling me which version of the mod you are using?
And yes, that sounds like a good idea for the lantern, I may try that out

**Comment by itsNordLord** [comment]
Dependencies:
`architectury-1.15.13-fabric`
`cloth-config-4.11.26-fabric`
`fabric-api-0.34.2+1.16`

Loaded Mods:
`brazier-3.0.6-fabric`

Log:
[latest.log](https://github.com/PssbleTrngle/Brazier/files/6550336/latest.log)

**Comment by PssbleTrngle** [comment]
To be completely honest, I do not know if I have tested cursed ash with fabric, I'll take a look into it

**Comment by PssbleTrngle** [comment]
I just checked, and cursed ash works on fabric
