### ISSUE TITLE
Crash on latest version when loading existing world

### ISSUE THREAD

**Issue by Foozey** [PssbleTrngle/Brazier#74]
**Describe the bug**
Just updated several mods, found that when loading my existing world the game kept closing itself with no crash report. Ended up narrowing it down to this. Previous versions work fine.

**To Reproduce**
Described above.

**Expected behavior**
World to load, no issues.

**Screenshots**
N/A.

**Version**
Modloader: Forge
Modloader Version: 36.1.24
Mod Version: 3.0.7

**Logs**
[debug.log](https://github.com/PssbleTrngle/Brazier/files/6574337/debug.log)
[latest.log](https://github.com/PssbleTrngle/Brazier/files/6574339/latest.log)

**Comment by Klouver-github** [comment]
Im having the same Issue, and I thought one of the mods I using is tripping. Cause i'm trying enjoy my McNuggets while warm up in my minecraft blanket, and so I had to figure out through minutes until now. Thank you for letting me know and we'll wait for bug fix

**Comment by PssbleTrngle** [comment]
Fixed in the next version
