### ISSUE TITLE
Stray ignore brazier

### ISSUE THREAD

**Issue by VelocIGamerBR** [PssbleTrngle/Brazier#75]
**Describe the bug**
stray ignore brazier and spawn without bow

**To Reproduce**
put brazier on alps foothills or alps (biomes o plenty) snowny_tundra ice_spikes and stray will be spawn without bow

i'm using
Complementary shaders 
Optfine G8 ultra

Print of my mods

![print mod 1](https://user-images.githubusercontent.com/83925949/120403331-5c4c4380-c31a-11eb-82e8-37ffbed6a47d.PNG)
![print mod 2](https://user-images.githubusercontent.com/83925949/120403337-5e160700-c31a-11eb-8dcd-939a76b3dbc8.PNG)

**Expected behavior**
not spawn stray in my land ;-; 

**Screenshots**
![2021-06-01_20 34 29](https://user-images.githubusercontent.com/83925949/120402801-5144e380-c319-11eb-8875-8560c99db3c6.png)
![2021-06-01_20 34 32](https://user-images.githubusercontent.com/83925949/120402810-56a22e00-c319-11eb-834c-5b0e36ad6f3e.png)
![2021-06-01_20 34 43](https://user-images.githubusercontent.com/83925949/120402817-5b66e200-c319-11eb-969d-b832e4e722b7.png)

**Version**
Modloader: Forge
Modloader Version: 1.16.5 - 36.1.24
Mod Version: 3.0.8

**Comment by VelocIGamerBR** [comment]
i put stray in blacklist after this and this bug keeps happening
my blacklist

{
  "replace": true,
  "values": [
    "minecraft:slime",
    "minecraft:magma_cube",
    "minecraft:hoglin",
    "minecraft:skeleton",
    "minecraft:creeper",
    "minecraft:zombie",
    "minecraft:enderman",
    "minecraft:zombie_villager",
    "minecraft:spider",
    "minecraft:stray",
    "eidolon:zombie_brute",
    "eidolon:wraith",
    "alexsmobs:soul_vulture",
    "mowziesmobs:barakoan_barakoana",
    "mowziesmobs:barakoana"
  ]
}

**Comment by VelocIGamerBR** [comment]
datapacks i'm using in my world

![data print](https://user-images.githubusercontent.com/83925949/120408506-8e16d780-c325-11eb-8a02-0900ed13b2d8.PNG)

i reset all my .minecraft and the problem keeps happening

**Comment by VelocIGamerBR** [comment]
https://www.mediafire.com/file/9n5rdtswv89ir9u/mods_and_datapacks.zip/file

mods and datapacks to make easy to find the problem

**Comment by PssbleTrngle** [comment]
Do you have charm installed or do you know if any of the mods do something with strays?

**Comment by VelocIGamerBR** [comment]
man i not tested, but in the mod dont have charm above i sent the images and the mods download

**Comment by PssbleTrngle** [comment]
I could not figure out which mod causes this, but it should be fixed in the next version

**Comment by VelocIGamerBR** [comment]
thanks
