### ISSUE TITLE
Cursed Ash doesnt work in my mod setup, having difficulty creating a Mobwhitelist through datapacks. 

### ISSUE THREAD

**Issue by Syriuslokan** [PssbleTrngle/Brazier#76]
Dear Modcreator, 

first of all im in love with this mod. Creating a such an immersive way (grind for materials, an adventurous search for the flame) to deactivate mobspawning. Nice to see the all the downloads proof ...a lot of us dont like simple easy ways. Effort and Reward !

Im having two problems. 

The Cursed Ash wont work, only a modded mob will spawn (Cockroach - Alex Mobs) on it. As my modsetup counts 60 upwards i truly understand that there could be some cross compatibility issues. No probs. 

The second problem as i couldn't get cursed ash to work was hitting a wall with whitelisting specific mods through datapacks.
After researching creating/installing datapacks, "making sure" the file structure within those datapacks is "correct" i just can't get it to work. The datapack is recorgnized by minecraft /datapack list, /datpack enable verify its there and running. So clearly there has to be an error im missing. The file structure has a bad setup  or the content of my brazier_whitelist is coded wrong or in the wrong place ?

Just for the sake of it, here's my modsetup , i understand the situtation with +60 mods and don't hold a breath bout it if it doesnt work
![modlist](https://user-images.githubusercontent.com/88188244/127637151-71a002a3-f7dc-42a2-aed6-49077dc779d5.PNG)

And here is a screen of my datapack and the file structure. As is had problems with the right file structure and didn't know if the brazier_whitelist was a .json where the mobs are added in to or brazier_whitelist is a normal folder containing  the different whitelisted .json mobs, i ended up doing kinda both :)

![Inkeddatapack file stucture_LI](https://user-images.githubusercontent.com/88188244/127639158-9d987904-b522-47b0-9bf7-e91dba4424bf.jpg)

I hope that's all the info needed.....not giving up on those datapacks :) This mod just soooo perfectly fits my style of playing MC.

Thank you for  your efforts

Peace

**Comment by PssbleTrngle** [comment]
Sorry for the long wait :/

No idea why the cursed ash won't work, but it does get funky with a lot of mods because spawn weights will be all over the place.
In order to fix your slime problem, you may need to also overwrite the  blacklist, because the default one is as follows:
```json
{
  "replace": false,
  "values": [
    "minecraft:slime",
    "minecraft:magma_cube",
    "minecraft:hoglin"
  ]
}
```

As you can see, it includes the slime. Just copy the file, set `replace` to `true` and remove  the slime line

**Comment by Syriuslokan** [comment]
Thanks for the answer. I appreciate taking the time to answer. The problem with the cursed ash was due to my sloppyness. The option "decorative" was set to true.  Im sure the problem was there. Testet and it seemed to work (spawns).  As for the blacklist ill overwrite it with your recommendations. Thanks alot. Cheers.
