### ISSUE TITLE
Brazier working through multiple dimensions

### ISSUE THREAD

**Issue by ghost** [PssbleTrngle/Brazier#77]
**Describe the bug**
A Brazier placed at 0,0 in the End is effecting both the Overworld and Nether. The center of each brazier field seems to line up with 0,0 in its respective dimension, and keeps the same range as the brazier placed in the end.

**To Reproduce**
-Go to end (unsure if this happens in Overworld and Nether)
-Build brazier tower under the end return portal at 0,0
-explore the overworld and nether with a torch to find the borders without a brazier

**Expected behavior**
As far as I'm aware, a brazier should only disable spawning in the local area, not potentially damaging farms in the nether or overworld

**Screenshots**
![2021-08-06_23 31 17](https://user-images.githubusercontent.com/84806713/128587989-64b90d9c-dda4-440a-b36a-b9279519155d.png)
![2021-08-06_23 32 18](https://user-images.githubusercontent.com/84806713/128587991-19405439-f904-4cc4-8fa0-130eef9f20e7.png)
![2021-08-06_23 32 36](https://user-images.githubusercontent.com/84806713/128587994-9c6c5ab5-2421-4960-901b-8bd77410be5d.png)
![2021-08-06_23 33 36](https://user-images.githubusercontent.com/84806713/128587996-c59c3975-7f20-46bf-b074-5cecafb30d7f.png)
![2021-08-06_23 34 48](https://user-images.githubusercontent.com/84806713/128587998-9bd85c05-d364-4812-b30e-265f0ad80bf2.png)
![2021-08-06_23 35 17](https://user-images.githubusercontent.com/84806713/128588001-b42d9aab-b761-44f6-b0f8-eb6ebc7dd0e6.png)

**Version**
Modloader: Fabric
Modloader Version: 1.16.5
Mod Version: 3.0.6

**Comment by PssbleTrngle** [comment]
Makes sense, that's something I always seem to forget when handling position-based logic in minecraft.
I'm taking some time of right now, but I have acknowledged it and will fix it as soon as I'm back

**Comment by ghost** [comment]
Ah, makes sense. Enjoy your time off!
