### ISSUE TITLE
Brazier mod crashes when the initial loading with forge 36.2.2 and 36.2.4 at least

### ISSUE THREAD

**Issue by Via-GitHub** [PssbleTrngle/Brazier#79]
**Describe the bug**
Brazier mod always crashes although I tried it without any other mods immediately after creating a new test profile. Strangely the mod had been normally launched several times before and I even built the spawn-preventing construct once in creative mode but I cannot reproduce the circumstance. Also tested with Architectury 1.21.29, 30, 31

**To Reproduce**
1) Make a new profile with Forge.
2) Install only Brazier mod and Architectury.
3) Launch Minecraft.

**Expected behavior**
The mod should be loaded to Mincraft 1.16.5.

**Screenshots**
![brazier](https://user-images.githubusercontent.com/51545487/131600641-9a72337c-f357-42fa-b0d7-f1eaa080a055.jpg)

**Version**
Modloader: Forge
Modloader Version: 36.2.2 and 36.2.4
Mod Version: 3.0.9

**Crash report file**
[crash-2021-09-01_10.48.03-fml.txt](https://github.com/PssbleTrngle/Brazier/files/7087756/crash-2021-09-01_10.48.03-fml.txt)

**Comment by PssbleTrngle** [comment]
Cloth Config is a requirement too, looks like a lot of people forget it
