### ISSUE TITLE
brazier_range_detector (possible bug)

### ISSUE THREAD

**Issue by Xaidee** [PssbleTrngle/Brazier#85]
Is the brazier_range_detector item tag actually used or is it meant to be? I'm wondering because I was experimenting and tried applying the tag to other items but the tag doesn't seem to do anything.
Really like this mod and its whole concept, thanks!

**Comment by PssbleTrngle** [comment]
You are correct, it seems like I actually forgot to check for the tag in the actual implementation.
I will check on it later and publish a fixed version

**Comment by Xaidee** [comment]
Okay awesome! appreciate the work ^-^

**Comment by PssbleTrngle** [comment]
Thanks, should be fixed in `4.0.2`
