### ISSUE TITLE
Rune Particles rendering in places they shouldn't

### ISSUE THREAD

**Issue by Xaidee** [PssbleTrngle/Brazier#88]
**Describe the bug**
A layer of vertical runes seem to be rendering 10 blocks above the structure, I made it ten blocks high and I think it might be an error in the code that's making the bottom row of runes render way to high. It doesn't seem to occur when the structure is 9 blocks high or less.

**To Reproduce**
Build a brazier structure 10 blocks high or more.

**Expected behavior**
Runes should render on the sides of all ten blocks instead of the bottom layer of the ten being rendered in the air above the structure.

**Screenshots**
![image](https://user-images.githubusercontent.com/59002946/183268457-1e17a499-b65c-43ca-9a9f-bdcdb53de64b.png)
![image](https://user-images.githubusercontent.com/59002946/183268514-18ddd262-f02b-428c-b8ba-62a952d68cf9.png)

**Version**
Modloader: Forge
Modloader Version: 40.1.68 (1.18.2)
Mod Version: 4.1.0

**Comment by PssbleTrngle** [comment]
Seems like I forgot to look up while testing
