### ISSUE TITLE
Separate the blocks in 2 tags

### ISSUE THREAD

**Issue by Subthy** [PssbleTrngle/Brazier#91]
### Describe the feature you have in mind.

Hello, so the blackstone and netherite blocks are under one tag, so you can just make the structure just out of blackstone or netherrite. I would like for you to create a second tag, that makes it so you need 2 block types for the multiblock structure. As shown in the picture, it doesn't work like that right now,

### Does this solve a particular problem?

Yes, as it makes it so you need only one block to make the structure.

**Comment by PssbleTrngle** [comment]
This has been an intentional decision, since you can pick and choose the blocks of conduits and beacons too.
If I would change this, I would definitely not make netherite blocks required, since that would be way too expensive

**Comment by Subthy** [comment]
Well, the example given is very miss leading I would say. Saying it's similar doesn't give a good enough explanation. I would suggest, you add images with the structure made from one block only then.

**Comment by PssbleTrngle** [comment]
I have decided to split them into two tags, which currently contain the same blocks, but can be overridden individually using a datapack
