### ISSUE TITLE
Block mod compatibility

### ISSUE THREAD

**Issue by SurgeXs** [PssbleTrngle/Brazier#94]
### Describe the feature you have in mind.

Currently, the chipped mod's variants of brazier compatible blocks do not work with the brazier.  Is it possible to use a regex of some sort to add compatibility, or maybe just hardcoding compatibility for mods?

**Comment by PssbleTrngle** [comment]
Should be entire possible using block tags (adding it to `brazier:brazier_base_blocks`).
You can try it out using a datapack, but I can definitely also add them as optional entries to the mod itself

**Comment by SurgeXs** [comment]
Would it be possible to add a config file to simplify the addition of base
blocks?

**Comment by PssbleTrngle** [comment]
Datapacks are the best and most versatile way to modify these kind of things, especially block tags.
It's easier than you probably think, I recommend you give it a try
